refact: Core.Render.Property to avoid Ur in input
Unfortunately, the approach here used currently doesn't work on GHC for
lack of multiplicity coercions. See

ghengin-core/Ghengin/Core/Render/Property.hs:373:3: error: [GHC-59840]
    GHC bug #19517: GHC currently does not support programs using GADTs or type families to witness equality of multiplicities
    |
373 |   case prop of
    |   ^^^^^^^^^^^^...